services:
  - type: web
    name: kanishkaa-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASS
        sync: false
      - key: DATABASE_URL
        sync: false